export const API_KEY = "58cf458382dd90a89d037a30b50b8ab1";
export const IMAGE_PATH = "https://image.tmdb.org/t/p/original/";
export const IMAGE_W500_PATH = "https://image.tmdb.org/t/p/w500/";
export const TRAILER_YOUTUBE_PATH = "https://www.youtube.com/embed/";

export const ACTION_TYPES = {
    GET_POPULAR_MOVIES_SWIPER: "GET_POPULAR_MOVIES_SWIPER",
    GET_REQUEST_RECOMENDED: "GET_REQUEST_RECOMENDED",
    GET_SUCCSES_RECOMENDED_MOVIES: " GET_SUCCSES_RECOMENDED_MOVIES",
    GET_FEILS_REQUESTS: "GET_FEILS_REQUESTS",
    GET_SUCCSES_TRAILER:"GET_SUCCSES_TRAILER",
    TOGGLE_MODAL: "TOGGLE_MODAL",
    SEARCH_MOVIES: " SEARCH_MOVIES",
    SEARCH_MODAL_OPEN:"SEARCH_MODAL_OPEN",
}